### ISSUE TITLE
:toBe(nil) doesnt work

### ISSUE THREAD

**Issue by luttje** [luttje/jestronaut#11]
Although `:toBeNil()` can be used, there's no reason `:toBe(nil)` shouldn't also succeed if the expected and actual are both nil.

**Comment by MathioLucas** [comment]
Fix for Issue #11:
Updated the toBe() matcher to support comparison with nil values. This should make sure :toBe(nil) works as intended when both the actual and expected values are nil.

**Comment by luttje** [comment]
Closed by #14.

Thanks again for contributing!
